### ISSUE TITLE
Missing pdfs

### ISSUE THREAD

**Issue by avoutsas67** [mynameisjanus/6431xProbability#1]
Dear Janus,

Many thanks for your excellent work. Can you please include include the PDFs required to build the tex file?

Many thanks for your help,

Achilleas

**Comment by mynameisjanus** [comment]
Thanks, Achilleas. I've uploaded them.

**Comment by avoutsas67** [comment]
That's excellent! Many thanks Janus, your cheatsheets are really good. 

Achilleas
