### ISSUE TITLE
How to edit and export cheatsheet to pdf

### ISSUE THREAD

**Issue by HongNguyen2301** [mynameisjanus/6431xProbability#3]
@mynameisjanus I found the probability cheatsheet really helpful. I am wondering which tool or web app I can use to edit the tex file and export the tex file to pdf? Thanks

**Comment by mynameisjanus** [comment]
Thanks! You can use texstudio or texmaker. I personally use texstudio in ubuntu. You can also use Overleaf online, just upload the entire repo to overleaf, although I think you can connect overleaf to github.

**Comment by HongNguyen2301** [comment]
@mynameisjanus I have tried with Overleaf which is so convinient. Thanks!

**Comment by mynameisjanus** [comment]
Sure, glad I could help!
